export const REQUEST_ROOMS = 'chat/REQUEST_ROOMS'
export const RECEIVED_ROOMS = 'chat/RECEIVED_ROOMS'
export const FAILURE_ROOMS = 'chat/FAILURE_ROOMS'

export const REQUEST_ROOM_D = 'chat/REQUEST_ROOM_D'
export const RECEIVED_ROOM_D = 'chat/RECEIVED_ROOM_D'
export const FAILURE_ROOM_D = 'chat/FAILURE_ROOM_D'



export const REQUEST_CREATE_ROOM = 'chat/REQUEST_CREATE_ROOM'
export const SUCCESS_CREATE_ROOM = 'chat/SUCCES_CREATE_ROOM'
export const FAILURE_CREATE_ROOM = 'chat/FAILURE_CREATE_ROOM'

export const REQUEST_NEW_MSG = 'chat/REQUEST_NEW_MSG'
export const RECEIVED_NEW_MSG = 'chat/RECEIVED_NEW_MSG'
export const FAILURE_NEW_MSG = 'chat/FAILURE_NEW_MSG'


export const REQUEST_NOTIFICATION = 'chat/REQUEST_NOTIFICATION'
export const RECEIVED_NOTIFICATION = 'chat/RECEIVED_NOTIFICATION'
export const FAILURE_NOTIFICATION = 'chat/FAILURE_NOTIFICATION'
export const NEW_NOTIFICATION = 'chat/NEW_NOTIFICATION'
export const DELETE_NOTIFICATION = 'chat/DELETE_NOTIFICATION'

export const REMOVE_ROOM = 'chat/REMOVE_ROOM'