export const REQUEST_JOBS = 'jobs/REQUEST_JOBS'
export const RECEIVED_JOBS = 'jobs/RECEIVED_JOBS'
export const FAILURE_JOBS = 'jobs/FAILURE_JOBS'
export const GET_JOB_ID = 'jobs/GET_JOB_ID'
export const APPLY_JOB = 'jobs/APPLY_JOB'
export const APPLY_JOB_SUCCESS = 'jobs/APPLY_JOB_SUCCESS'
export const CHECK_APPLIED_JOBS = 'jobs/CHECK_APPLIED_JOBS'
