export const REQUEST_CANDIDATE = ' candidate/REQUEST_CANDIDATE'
export const RECEIVED_CANDIDATE = 'candidate/RECEIVED_CANDIDATE'
export const FAILURE_CANDIDATE = ' candidate/FAILURE_CANDIDATE'

export const REQUEST_CANDIDATE_D = ' candidate/REQUEST_CANDIDATE_D'
export const RECEIVED_CANDIDATE_D = 'candidate/RECEIVED_CANDIDATE_D'
export const FAILURE_CANDIDATE_D  = ' candidate/FAILURE_CANDIDATE_D'
