export const categories = [
  "Barista și Barman",
  "Frumuseţe si Bunastare",
  "Îngrijitorii și sănătatea",
  "Bucatar",
  "Curățenie",
  "Constructie",
  "Sofer",
  "Tehnologie si Inginerie",
  "Educaţie",
  "Evenimente și promovare",
  "Bucătărie portar",
  "Oficiu si Admin",
  "Vanzari si Marketing",
  "Ospătar sau servitoare",
  "Depozit",
  "Alte",
];
